### ISSUE TITLE
Stuck on "Loading today.."

### ISSUE THREAD

**Issue by cygnoir** [exist-sense/core#2]
Hi! I'm pretty excited to try Exist Sense, but so far I'm unable to do anything but login. The page is stuck on "Loading today.." I have tried this in Firefox and Safari on macOS 10.13.6 with the same result.

**Comment by qreeves** [comment]
Sorry to hear you're having issues. If you can, are you able to provide the output from your browser's console? This may contain sensitive information, so please feel free to email exist-sense@redeclipse.net with the output so we can keep it private. In Firefox you can find this under `Tools > Web Developer > Web Console`.

It should look a little like this (collapsed):
![image](https://user-images.githubusercontent.com/3297929/45406415-d12e4980-b6a9-11e8-9dab-ddd51f00f8ae.png)

**Comment by qreeves** [comment]
Sorry for the delay here. This no longer appears to be an issue with the most recent Firefox and Exist Sense. Please let me know if you continue having issues and I'll be happy to look into it further.
